### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by loiseaujc** [nekStab/LightKrylov#80]
At the moment, the error handling is quite rudimentary. This is an area where we code improve things quite bit to strive for a better code. I'm not entirely sure yet how to address this issue correctly. From what I can see, the way it is being done in the `stdlib_linalg` module seems like a good starting point. In general, I believe that following the standard sets by `stdlib` is good idea. I'll look more into that about the conference next week.

**Comment by Simkern** [comment]
I ran into another enhancement suggestion while upgrading `LightROM` to the new API in `LightKrylov`. As the verbosity setting for `qr` is now set to `.true.` by default which generated a number of outputs during the run, but it does not allow to simply backtrace to which call to `qr` actually throws the warning.

We should follow each of the base `LightKrylov` calls in the core with a line to the effect of
```
if (info /= 0) write(output_unit,*)  '  [<name_of_caller_routine>] Info: Colinear vectors detected in QR, column ', info
```
where we have set `info` to the colinear column number.

We could generalize this to the whole toolbox to have a generic `check_info` function that will check the info flag to write something like this in the output:
```
'[ arnoldi / qr ] : Info: Colinear vectors detected in QR, column ', info, ' step', k
```
What do you think about this? Are there any other requirements for the error_check?

This should be separate from the errors, which will need to throw exceptions which could be handled in a way similar to `stdlib`.

**Comment by Simkern** [comment]
The logging tools I implemented are a first pass to unify the info/error handling.

There are still a few open tasks related to logging/error handling:

- [ ] `gmres` and `cg` have only very rudimentary error handling as of now (only informing about the number of iterations to convergence). This could be improved to allow more fine-grained information about the solver.
- [ ] Add dedicated logfile in order to not clutter the terminal.

Note: For now, the logger only logs `information`, `warning` and `error` and the logger is set to abort on error.
